[project]
name = "MoE_testing_framework"
version = "1.0.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "pytest>=8.3.4",
    "rich>=13.9.4",
]
